using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using Unity.XR.CoreUtils;

public class MenuController : MonoBehaviour
{
    [Header("Scenes")]
    [Tooltip("Content scene loaded by the tutorial button. Must be listed in " +
             "File > Build Settings, or LoadSceneAsync cannot find it by name at runtime.")]
    [SerializeField] private string tutorialSceneName = "Tutorial";

    [Tooltip("This menu's own scene. Unloaded once the content scene is up.")]
    [SerializeField] private string mainMenuSceneName = "MainMenu";

    // Only used by the fallback path below; the transition controller has its own guard.
    private bool _isSwitching;

    [SerializeField] private GameObject mainMenuRoot;
    [SerializeField] private Transform menuStandingPoint;
    private bool isLoadingRunSystem;

    [Header("Map")]
    [Tooltip("Scene loaded by the Map button: the tabletop route model seen before the first " +
             "unguided run. Generated by Tools > VR Full Route > Build Route Map Scene, which also " +
             "adds it to Build Settings.")]
    [SerializeField] private string routeMapSceneName = "RouteMap";

    [Tooltip("Seconds to fade out of the menu and into the map.")]
    [SerializeField] private float mapFadeSeconds = 0.5f;

    // ------------------------------------------------------------------ the menu area
    // "In the menu" is the participant standing in the menu park, whichever page is up -
    // including the researcher screen, which hides the menu panel itself. It ends when a run or
    // the Map takes over (both hide the menu but leave this scene loaded) or when the tutorial
    // unloads this scene, and starts again when the menu is shown on the way back.
    //
    // Tracked explicitly rather than by this component's OnEnable/OnDisable: it sits on the menu
    // panel, so the researcher screen hiding that panel would otherwise count as leaving.
    //
    // While in the menu:
    //   - walking is held off (snap turning, head look and the pointer still work);
    //   - the park around the menu (MenuEnvironment, built by Tools > VR Full Route > Build Main
    //     Menu Park) is shown. It is hidden otherwise: the Map and the runs are built 500 m away
    //     in the same world, so it would otherwise stand on their horizon.
    public const string EnvironmentRootName = "MenuEnvironment";

    private bool _holdingWalking;
    private GameObject _environment;

    private void SetInMenu(bool inMenu)
    {
        ControllerHandednessManager hands = ControllerHandednessManager.Instance;
        if (inMenu && !_holdingWalking && hands != null)
        {
            hands.SuspendWalking(this);
            _holdingWalking = true;
        }
        else if (!inMenu && _holdingWalking)
        {
            hands?.ResumeWalking(this);
            _holdingWalking = false;
        }

        if (_environment == null) _environment = FindEnvironment();
        if (_environment != null && _environment.activeSelf != inMenu) _environment.SetActive(inMenu);
    }

    /// <summary>The park's root object in this scene, if it has been built. Found active or not.</summary>
    private GameObject FindEnvironment()
    {
        foreach (GameObject root in gameObject.scene.GetRootGameObjects())
            if (root.name == EnvironmentRootName) return root;
        return null;
    }

    private void OnDestroy()
    {
        // The tutorial unloads this scene: hand walking back (it returns once the transition's own
        // hold ends, not while the view is still dark).
        if (_holdingWalking) ControllerHandednessManager.Instance?.ResumeWalking(this);
        _holdingWalking = false;
    }

    private void Start()
    {
        SetInMenu(true);

        TeleportPlayerToMenu();

        // Researcher-only participant ID screen: hold both thumbsticks in for 3 s on this menu.
        ResearcherScreen.Attach(mainMenuRoot);

        // Ticks off completed modules, padlocks the ones not yet reached, highlights the next.
        ModuleCompletionView.Attach(mainMenuRoot);
    }

    public void onRunSystemButtonClick()
    {
        Debug.Log("Run System Button Clicked");
    }

    // ------------------------------------------------------------------ study modules
    // The intervention runs four modules in this order, each followed by its own survey, so
    // each records its own run type (the CSVs' run_type column and the session log). Only
    // "guided" shows the route line; the three unguided modules are the same run.
    // With a participant ID set they open one at a time, after the Map (ModuleProgress.Sequence).
    public const string ModuleUnguided1 = "unguided_1";
    public const string ModuleGuided = "guided";
    public const string ModuleUnguided2a = "unguided_2a";
    public const string ModuleUnguided2b = "unguided_2b";

    /// <summary>Module 1: "1  Unguided". (Kept its old name so the existing button stays wired.)</summary>
    public void onUnguidedButtonClick() => StartModule(ModuleUnguided1);

    /// <summary>Module 2: "2  Guided".</summary>
    public void onGuidedButtonClick() => StartModule(ModuleGuided);

    /// <summary>Module 3: "3  Unguided 2.a".</summary>
    public void onUnguided2aButtonClick() => StartModule(ModuleUnguided2a);

    /// <summary>Module 4: "4  Unguided 2.b".</summary>
    public void onUnguided2bButtonClick() => StartModule(ModuleUnguided2b);

    /// <summary>
    /// Any module by run type - for a further module button: wire its On Click to this and
    /// type its run type into the box. Only the run type "guided" shows the route line.
    /// </summary>
    public void onModuleButtonClick(string runType) => StartModule(runType);

    // ------------------------------------------------------------------ map
    /// <summary>
    /// "Map", at the top of Select Module: a 60 s look at a tabletop model of the route before
    /// the first unguided run. RouteMapView runs the visit and brings the participant back here.
    /// </summary>
    public void onMapButtonClick()
    {
        if (isLoadingRunSystem || !CanStart(ModuleProgress.MapModule))
            return;
        Debug.Log("Map button clicked");
        StartCoroutine(LoadRouteMap());
    }

    private IEnumerator LoadRouteMap()
    {
        isLoadingRunSystem = true;

        ScreenFader fader = ScreenFader.Instance;
        if (fader != null)
            yield return fader.FadeTo(1f, mapFadeSeconds);

        if (!SceneManager.GetSceneByName(routeMapSceneName).isLoaded)
        {
            AsyncOperation load = SceneManager.LoadSceneAsync(routeMapSceneName, LoadSceneMode.Additive);
            if (load == null)
            {
                Debug.LogError($"{routeMapSceneName} could not be loaded. Run Tools > VR Full Route > " +
                               "Build Route Map Scene, which also adds it to Build Settings.", this);
                if (fader != null) fader.FadeIn(mapFadeSeconds);
                isLoadingRunSystem = false;
                yield break;
            }
            yield return load;
        }

        RouteMapView view = null;
        Scene mapScene = SceneManager.GetSceneByName(routeMapSceneName);
        if (mapScene.IsValid() && mapScene.isLoaded)
        {
            foreach (GameObject root in mapScene.GetRootGameObjects())
            {
                view = root.GetComponentInChildren<RouteMapView>(true);
                if (view != null) break;
            }
        }

        if (view == null)
        {
            Debug.LogError($"No RouteMapView in {routeMapSceneName}. Re-run Tools > VR Full Route > " +
                           "Build Route Map Scene.", this);
            if (mapScene.IsValid() && mapScene.isLoaded)
                SceneManager.UnloadSceneAsync(mapScene);
            if (fader != null) fader.FadeIn(mapFadeSeconds);
            isLoadingRunSystem = false;
            yield break;
        }

        view.Begin();
        isLoadingRunSystem = false;

        // The fade back in runs on the fader (Bootstrap), and the menu is hidden last: this
        // controller sits inside the menu, so hiding it ends this coroutine.
        if (fader != null) fader.FadeIn(mapFadeSeconds);
        SetInMenu(false);
        if (mainMenuRoot != null)
            mainMenuRoot.SetActive(false);
    }

    private void StartModule(string runType)
    {
        if (isLoadingRunSystem || string.IsNullOrWhiteSpace(runType) || !CanStart(runType.Trim()))
            return;
        Debug.Log($"Module button clicked: {runType}");
        isLoadingRunSystem = true;

        // Loaded behind the same fade as the tutorial: dark, load, place the participant at the
        // bus stop, then fade in. Runs on SceneTransitionController (Bootstrap), so hiding the
        // menu - this controller's own object - does not cut it short.
        SceneTransitionController transition = SceneTransitionController.Instance;
        if (transition != null && transition.RunInDark(LoadRunSystem(runType.Trim())))
            return;

        Debug.LogWarning("[MenuController] No SceneTransitionController in Bootstrap (or one already " +
                         "running) - loading the module without a fade.", this);
        StartCoroutine(LoadRunSystem(runType.Trim()));
    }

    /// <summary>
    /// Only the next module in the order can be started (ModuleCompletionView also switches the
    /// other buttons off); this is the same check for anything else that calls these methods.
    /// Always true with no participant ID set.
    /// </summary>
    private bool CanStart(string module)
    {
        string id = StudySession.ParticipantId;
        if (ModuleProgress.IsUnlocked(id, module))
            return true;

        if (ModuleProgress.IsCompleted(id, module))
            Debug.Log($"'{module}' is already completed for {id}. To repeat it, reset progress on the " +
                      "researcher screen (hold both thumbsticks for 3 s on the main menu).", this);
        else if (ModuleProgress.IsSkipped(id, module))
            Debug.Log($"'{module}' was skipped for {id}. To do it after all, reset progress on the researcher screen.", this);
        else
            Debug.Log($"'{module}' is locked for {id}: next is '{ModuleProgress.NextModule(id) ?? "nothing (all done)"}'. " +
                      "Modules open in order: Map, 1 Unguided, 2 Guided, 3 Unguided 2.a, 4 Unguided 2.b. " +
                      "The researcher screen's Skip module moves past one that can't be finished.", this);
        return false;
    }

    public void ShowMainMenu()
    {
        SetInMenu(true);
        TeleportPlayerToMenu();

        if (mainMenuRoot != null)
            mainMenuRoot.SetActive(true);
        else
            Debug.LogWarning("MenuController has no main menu root assigned.", this);
    }

    private void TeleportPlayerToMenu()
    {
        XROrigin xrOrigin = FindFirstObjectByType<XROrigin>();

        if (XRPlayerTeleport.MoveToStandingPoint(
                xrOrigin,
                menuStandingPoint,
                this))
        {
            Debug.Log("Player returned to the main menu.", this);
        }
    }

    private IEnumerator LoadRunSystem(string runType)
    {
        Debug.Log("Loading Run System.", this);
        isLoadingRunSystem = true;

        AsyncOperation loadOperation =
            SceneManager.LoadSceneAsync("RunSystem", LoadSceneMode.Additive);

        if (loadOperation == null)
        {
            Debug.LogError("RunSystem could not be loaded.", this);
            isLoadingRunSystem = false;
            yield break;
        }

        yield return loadOperation;
        Debug.Log("RunSystem scene loaded.", this);

        RunSystemController runSystemController =
            FindFirstObjectByType<RunSystemController>();

        if (runSystemController == null)
        {
            Debug.LogError("RunSystemController could not be found.", this);
            isLoadingRunSystem = false;
            yield break;
        }

        runSystemController.StartRun(runType);

        // Cleared before hiding the menu: on the fallback path this coroutine runs on the menu
        // itself, and hiding it stops the coroutine.
        isLoadingRunSystem = false;
        SetInMenu(false);
        if (mainMenuRoot != null)
            mainMenuRoot.SetActive(false);
    }

    public void onTutorialButtonClick()
    {
        Debug.Log("Tutorial Button Clicked");
        SwitchToContentScene(tutorialSceneName);
    }

    /// <summary>
    /// Hands the swap to SceneTransitionController in Bootstrap, which fades the view out,
    /// preloads, places the player at the scene's spawn point and fades back in.
    ///
    /// Falls back to an unfaded additive swap if that controller is missing, so a misconfigured
    /// Bootstrap degrades to "works but looks abrupt" rather than "button does nothing".
    /// </summary>
    private void SwitchToContentScene(string sceneName)
    {
        if (string.IsNullOrEmpty(sceneName)) return;

        if (SceneTransitionController.Instance != null)
        {
            SceneTransitionController.Instance.SwitchTo(sceneName, mainMenuSceneName);
            return;
        }

        Debug.LogWarning("[MenuController] No SceneTransitionController found in Bootstrap - " +
                         "switching without a fade.", this);
        SwitchUnfaded(sceneName);
    }

    /// <summary>
    /// Fallback. Still ADDITIVE: a plain SceneManager.LoadScene would unload Bootstrap along
    /// with the menu, destroying XRPlayerRig, the XR Interaction Manager, the EventSystem and
    /// the ControllerHandednessManager - and the tutorial scene has no rig of its own.
    /// </summary>
    private async void SwitchUnfaded(string sceneName)
    {
        if (_isSwitching) return;
        _isSwitching = true;

        try
        {
            if (!SceneManager.GetSceneByName(sceneName).isLoaded)
            {
                await SceneManager.LoadSceneAsync(sceneName, LoadSceneMode.Additive);
            }

            Scene loaded = SceneManager.GetSceneByName(sceneName);
            if (loaded.IsValid() && loaded.isLoaded)
            {
                SceneManager.SetActiveScene(loaded);
            }

            Scene menu = SceneManager.GetSceneByName(mainMenuSceneName);
            if (menu.IsValid() && menu.isLoaded)
            {
                await SceneManager.UnloadSceneAsync(menu);
            }
        }
        finally
        {
            _isSwitching = false;
        }
    }
}
